version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: stateful_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: dashboard
      POSTGRES_PASSWORD: dashboard
      POSTGRES_DB: dashboard
    ports:
      - '5432:5432'
    command: ["postgres","-c","shared_preload_libraries=pg_stat_statements"]
    volumes:
      - ./pg/init:/docker-entrypoint-initdb.d:ro
  redis:
    image: redis:7
    container_name: stateful_redis
    restart: unless-stopped
    ports:
      - '6379:6379'

  mysql:
    image: mysql:8.0
    container_name: stateful_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: dashboard
      MYSQL_DATABASE: dashboard
      MYSQL_USER: dashboard
      MYSQL_PASSWORD: dashboard
    ports:
      - '3306:3306'
    command: 
      - --performance-schema=ON
      - --performance-schema-instrument='statement/%=ON'
      - --performance-schema-consumer-statements-digest=ON

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: stateful_zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: stateful_kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  opensearch:
    image: opensearchproject/opensearch:2
    container_name: stateful_opensearch
    restart: unless-stopped
    environment:
      discovery.type: single-node
      plugins.security.disabled: true
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - '9200:9200'
      - '9600:9600'
